name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    # needs: [build, test]
    if: github.ref_name == 'main'
    steps:
      - name: deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.render.com/deploy/${{ secrets.STAGING_DEPLOY_KEY }}&ref=${{ github.sha }}"
