name: Tests jest workflow
run-name: Run workflow about tests jest

on:
  workflow_run:
    workflows: [Typescript workflow build]
    types:
      - completed
jobs:
  success-case:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Testing app with Jest
        run: npm run test && echo '✅ ✅ Tests passed!'
